territory_fronts=true
yellow_split=true
strategic_operations=true
yellow_civil_war=true
supply_pressure=true
war_memory=false
rival_commanders=false
flagship_operations=false
boarding_rescue=false
alternative_campaigns=false
cooperative_command_prototype=false
focused_faction_attacks=true
multiplayer_custom_battle=false
multiplayer_custom_missions=false
