public enum CampaignShipProvenance {
    PLAYER_ROSTER,
    ALLIED_CAMPAIGN_FLEET,
    TEMPORARY_COALITION_SUPPORT,
    CIVILIAN,
    MISSION_ESCORT,
    ENEMY_CAMPAIGN_FLEET,
    TACTICAL_ONLY_SCRIPTED,
    CAMPAIGN_FORCE,
    UNKNOWN
}
