public enum CustomWeaponRuntimeBehavior {
    DIRECT_PROJECTILE,
    HOMING_PROJECTILE,
    INTERCEPTOR,
    BEAM,
    BURST_PROJECTILE,
    CONE_PROJECTILE,
    PROXIMITY_PROJECTILE,
    ARCING_PROJECTILE
}
