import app.config.ExperienceSettings;
import app.config.GameConfig;
import app.config.GameMode;

import javax.imageio.ImageIO;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Properties;
import java.util.zip.CRC32;

/** Captures deterministic production screenshot targets and compares them to stored visual signatures. */
public final class ScreenshotRegressionHarness {
    public static final Path DEFAULT_BASELINE = Path.of("config", "screenshot_baselines.properties");
    public static final Path DEFAULT_OUTPUT_DIR = Path.of("build", "reports", "visual-regression");
    private static final int VIEW_W = 1280;
    private static final int VIEW_H = 720;
    private static final int HASH_W = 32;
    private static final int HASH_H = 18;

    public record Capture(String target, String signature, int opaquePixels, int colorBuckets, Path imagePath) {}
    public record Result(List<Capture> captures, List<String> errors, Path baselinePath, Path outputDir) {
        public boolean passed() {
            return errors.isEmpty();
        }
    }

    private ScreenshotRegressionHarness() {}

    public static void main(String[] args) throws Exception {
        boolean strict = hasArg(args, "--strict");
        boolean updateBaseline = hasArg(args, "--update-baseline");
        Path baseline = pathArg(args, "--baseline=", DEFAULT_BASELINE);
        Path output = pathArg(args, "--output=", DEFAULT_OUTPUT_DIR);
        Result result = run(baseline, output, strict, updateBaseline);
        for (Capture capture : result.captures()) {
            System.out.println("[screenshot-regression] " + capture.target() + " " + capture.signature()
                    + " opaque=" + capture.opaquePixels() + " buckets=" + capture.colorBuckets()
                    + " png=" + capture.imagePath());
        }
        if (result.passed()) {
            System.out.println("[screenshot-regression] checks: PASS");
        } else {
            for (String error : result.errors()) System.err.println("[screenshot-regression] " + error);
            System.out.println("[screenshot-regression] checks: FAIL");
            if (strict) System.exit(1);
        }
    }

    public static Result run(Path baselinePath, Path outputDir, boolean strict, boolean updateBaseline) throws IOException {
        Path resolvedBaseline = baselinePath == null ? DEFAULT_BASELINE : baselinePath;
        Path resolvedOutput = outputDir == null ? DEFAULT_OUTPUT_DIR : outputDir;
        Files.createDirectories(resolvedOutput);
        Files.createDirectories(resolvedOutput.resolve("screenshots"));

        ProductionReadinessLongevitySystem.State production = ProductionReadinessLongevitySystem.bootstrap(0L);
        List<String> targets = production.art.regressionScreenshots;
        Properties expected = loadProperties(resolvedBaseline);
        Properties actual = new Properties();
        List<Capture> captures = new ArrayList<>();
        List<String> errors = new ArrayList<>();

        for (String target : targets) {
            BufferedImage image = capture(target);
            Path imagePath = resolvedOutput.resolve("screenshots").resolve(target + ".png");
            ImageIO.write(image, "png", imagePath.toFile());

            Capture capture = analyze(target, image, imagePath);
            captures.add(capture);
            actual.setProperty(target, capture.signature());
            if (capture.opaquePixels() < (VIEW_W * VIEW_H) / 3) {
                errors.add(target + ": rendered too few opaque pixels");
            }
            if (capture.colorBuckets() < 18) {
                errors.add(target + ": rendered with too little color variation");
            }
            String expectedSignature = expected.getProperty(target, "").trim();
            if (!updateBaseline && strict && expectedSignature.isEmpty()) {
                errors.add(target + ": missing baseline signature in " + resolvedBaseline);
            } else if (!updateBaseline && !expectedSignature.isEmpty()
                    && !expectedSignature.equals(capture.signature())) {
                errors.add(target + ": signature drift expected " + expectedSignature
                        + " but was " + capture.signature());
            }
        }

        Path actualPath = resolvedOutput.resolve("actual-signatures.properties");
        try (OutputStream out = Files.newOutputStream(actualPath)) {
            actual.store(out, "Generated by ScreenshotRegressionHarness");
        }
        if (updateBaseline) {
            Path parent = resolvedBaseline.getParent();
            if (parent != null) Files.createDirectories(parent);
            try (OutputStream out = Files.newOutputStream(resolvedBaseline)) {
                actual.store(out, "Screenshot regression baselines. Regenerate with gradlew screenshotRegression --args=\"--update-baseline\" after approved visual changes.");
            }
        }
        return new Result(List.copyOf(captures), List.copyOf(errors), resolvedBaseline, resolvedOutput);
    }

    public static BufferedImage capture(String target) {
        GameContext ctx = contextForTarget(target);
        BufferedImage image = new BufferedImage(VIEW_W, VIEW_H, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = image.createGraphics();
        try {
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
            GameRenderSystem.render(ctx, g2, VIEW_W, VIEW_H);
        } finally {
            g2.dispose();
        }
        return image;
    }

    private static GameContext contextForTarget(String target) {
        String normalized = (target == null ? "" : target).trim().toLowerCase(Locale.US);
        return switch (normalized) {
            case "campaign-map" -> campaignMapContext(UiState.CampaignCommandTab.NAV, false);
            case "fleet-board" -> campaignMapContext(UiState.CampaignCommandTab.FLEET, false);
            case "strike-tab" -> campaignMapContext(UiState.CampaignCommandTab.STRIKES, false);
            case "accessibility-hud" -> campaignMapContext(UiState.CampaignCommandTab.RESOURCES, true);
            case "tactical-hud" -> tacticalHudContext(false);
            default -> campaignMapContext(UiState.CampaignCommandTab.NAV, false);
        };
    }

    private static GameContext campaignMapContext(UiState.CampaignCommandTab tab, boolean accessibility) {
        ExperienceSettings experience = ExperienceSettings.defaults();
        if (accessibility) {
            experience.highContrastHud = true;
            experience.reducedFlash = true;
            experience.reducedScreenShake = true;
            experience.uiTextScale = 1.25;
            experience.subtitleScale = 1.35;
            experience.colorblindPalette = ExperienceSettings.ColorblindPalette.DEUTERANOPIA;
        }
        GameContext ctx = new GameContext(new GameConfig(GameMode.CAMPAIGN_OPS, 5000, 5000,
                true, 20260602L, false).withExperience(experience));
        ctx.campaignUnlockProfile = null;
        SpawnSystem.initWorld(ctx);
        ctx.state = GameState.MAP;
        ctx.ui.mapOpen = true;
        ctx.ui.campaignCommandTab = tab == null ? UiState.CampaignCommandTab.NAV : tab;
        ctx.ui.hudDetail = accessibility ? GameContext.HudDetail.FULL : GameContext.HudDetail.COMPACT;
        if (ctx.campaign != null) {
            ctx.campaign.strategicOvermapMode = true;
            ctx.campaign.introSequenceActive = false;
            ctx.campaign.missionIntroTimer = 0.0;
            ctx.campaign.sectorElapsed = Math.max(ctx.campaign.sectorElapsed, 45.0);
        }
        return ctx;
    }

    private static GameContext tacticalHudContext(boolean accessibility) {
        ExperienceSettings experience = ExperienceSettings.defaults();
        if (accessibility) {
            experience.highContrastHud = true;
            experience.uiTextScale = 1.2;
        }
        GameContext ctx = new GameContext(new GameConfig(GameMode.SHOWCASE, 5000, 5000,
                true, 20260603L, false).withExperience(experience));
        SpawnSystem.initWorld(ctx);
        ctx.ui.tacticalViewEnabled = true;
        ctx.ui.hudDetail = GameContext.HudDetail.FULL;
        if (ctx.player != null) {
            CameraSystem.update(ctx, VIEW_W, VIEW_H);
            ctx.cursorWorldX = ctx.player.x + 180.0;
            ctx.cursorWorldY = ctx.player.y;
        }
        return ctx;
    }

    private static Capture analyze(String target, BufferedImage image, Path imagePath) {
        CRC32 crc = new CRC32();
        int opaque = 0;
        boolean[] buckets = new boolean[64];
        long lumaSum = 0L;
        for (int y = 0; y < HASH_H; y++) {
            for (int x = 0; x < HASH_W; x++) {
                int sample = averagedPixel(image, x, y);
                byte[] bytes = Integer.toHexString(sample).getBytes(StandardCharsets.US_ASCII);
                crc.update(bytes, 0, bytes.length);
            }
        }
        for (int y = 0; y < image.getHeight(); y += 4) {
            for (int x = 0; x < image.getWidth(); x += 4) {
                int argb = image.getRGB(x, y);
                int alpha = (argb >>> 24) & 0xff;
                if (alpha > 12) opaque += 16;
                int r = (argb >>> 16) & 0xff;
                int g = (argb >>> 8) & 0xff;
                int b = argb & 0xff;
                int luma = (r * 30 + g * 59 + b * 11) / 100;
                lumaSum += luma;
                buckets[Math.min(buckets.length - 1, luma / 4)] = true;
            }
        }
        int bucketCount = 0;
        for (boolean bucket : buckets) if (bucket) bucketCount++;
        long samples = Math.max(1L, (image.getWidth() / 4L) * (image.getHeight() / 4L));
        long meanLuma = lumaSum / samples;
        String signature = image.getWidth() + "x" + image.getHeight()
                + "|opaque=" + opaque
                + "|luma=" + meanLuma
                + "|crc=" + Long.toHexString(crc.getValue());
        return new Capture(target, signature, opaque, bucketCount, imagePath);
    }

    private static int averagedPixel(BufferedImage image, int cellX, int cellY) {
        int minX = cellX * image.getWidth() / HASH_W;
        int maxX = Math.max(minX + 1, (cellX + 1) * image.getWidth() / HASH_W);
        int minY = cellY * image.getHeight() / HASH_H;
        int maxY = Math.max(minY + 1, (cellY + 1) * image.getHeight() / HASH_H);
        long a = 0;
        long r = 0;
        long g = 0;
        long b = 0;
        long n = 0;
        for (int y = minY; y < maxY; y += 3) {
            for (int x = minX; x < maxX; x += 3) {
                int argb = image.getRGB(x, y);
                a += (argb >>> 24) & 0xff;
                r += (argb >>> 16) & 0xff;
                g += (argb >>> 8) & 0xff;
                b += argb & 0xff;
                n++;
            }
        }
        if (n <= 0) return 0;
        int qa = (int) ((a / n) / 16);
        int qr = (int) ((r / n) / 16);
        int qg = (int) ((g / n) / 16);
        int qb = (int) ((b / n) / 16);
        return (qa << 12) | (qr << 8) | (qg << 4) | qb;
    }

    private static Properties loadProperties(Path path) throws IOException {
        Properties properties = new Properties();
        if (path == null || !Files.exists(path)) return properties;
        try (InputStream in = Files.newInputStream(path)) {
            properties.load(in);
        }
        return properties;
    }

    private static boolean hasArg(String[] args, String expected) {
        if (args == null || expected == null) return false;
        for (String arg : args) if (expected.equals(arg)) return true;
        return false;
    }

    private static Path pathArg(String[] args, String prefix, Path fallback) {
        if (args == null || prefix == null) return fallback;
        for (String arg : args) {
            if (arg != null && arg.startsWith(prefix)) return Path.of(arg.substring(prefix.length()));
        }
        return fallback;
    }
}
