#Main menu settings
#Mon Mar 09 01:10:45 EDT 2026
fullscreen=false
mapIndex=0
modeName=RESOURCE_RUSH
randomEvents=false
seedText=0
version=1
voiceCaptionsEnabled=true
voiceVolumeCaptain=1.0
voiceVolumeEngineering=1.0
voiceVolumeHelm=1.0
voiceVolumeScience=1.0
voiceVolumeTactical=1.0
