#Main menu settings
#Thu Mar 19 18:09:22 EDT 2026
mapIndex=0
modeName=SHOOTING_RANGE
playerTeamId=0
randomEvents=false
seedText=21
version=1
voiceCaptionsEnabled=true
voiceVolumeCaptain=1.0
voiceVolumeEngineering=1.0
voiceVolumeHelm=1.0
voiceVolumeScience=1.0
voiceVolumeTactical=1.0
